version: '3.8'

services:
  db:
    image: postgres
    container_name: db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    healthcheck:
      test: pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}
      interval: 2s
      timeout: 2s
      retries: 3
    volumes:
      - ./postgres-data:/var/lib/postgresql/data

  migrate:
    image: stashunter/todolist:${GITHUB_REF_NAME}-${GITHUB_RUN_ID}
    container_name: migrate
    command: >
      sh -c "python manage.py makemigrations && python manage.py migrate"
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - .env:/todolist/.env

  api:
    image: stashunter/todolist:${GITHUB_REF_NAME}-${GITHUB_RUN_ID}
    container_name: api
    command: >
      sh -c "python manage.py collectstatic -c --no-input 
      && gunicorn diploma_project_pd12.wsgi:application -w 4 -b 0.0.0.0:8000"
    depends_on:
      - migrate
    volumes:
      - .env:/todolist/.env
      - django_static:/todolist/static

  frontend:
    image: sermalenk/skypro-front:lesson-35
    container_name: frontend
    ports:
      - "80:80"
    depends_on:
      - api
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - django_static:/usr/share/nginx/html/static

volumes:
  django_static: