version: '3.8'

services:
  db:
    image: postgres
    container_name: db
    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: userpassword
      POSTGRES_DB: databasename
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "username", "-d", "databasename"]
      interval: 2s
      timeout: 2s
      retries: 5
    volumes:
      - postgres-data:/var/lib/postgresql/data

  migrate:
    build: .
    container_name: migrate
    command: python manage.py migrate
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env

  api:
    build: .
    container_name: api
    command: >
      sh -c "python manage.py collectstatic -c --no-input 
      && gunicorn diploma_project_pd12.wsgi:application -w 4 -b 0.0.0.0:8000"
    depends_on:
      - migrate
    env_file:
      - .env
    volumes:
      - django_static:/todolist/static

  frontend:
    image: sermalenk/skypro-front:lesson-36
    container_name: frontend
    ports:
      - "80:80"
    depends_on:
      - api
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - django_static:/usr/share/nginx/html/static

volumes:
  postgres_data:
  django_static: