version: '3.8'

services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: todolistuser
      POSTGRES_PASSWORD: todolistpassword
      POSTGRES_DB: todolist_postgres
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "todolistuser", "-d", "todolist_postgres"]
      interval: 2s
      timeout: 2s
      retries: 5

  migrate:
    build: .
    command: python manage.py migrate
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env

  api:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/todolist
    ports:
      - "8000:8000"
    depends_on:
      - migrate
    env_file:
      - .env

  frontend:
    image: sermalenk/skypro-front:lesson-38
    ports:
      - "80:80"
    depends_on:
      - api