version: '3.8'

services:
  database:
    image: postgres
    container_name: database
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    healthcheck:
      test: pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}
      interval: 2s
      timeout: 2s
      retries: 3
    volumes:
      - ./postgres-data:/var/lib/postgresql/data

  tests:
    image: stashunter/todolist:${GITHUB_REF_NAME}-${GITHUB_RUN_ID}
    container_name: tests
    command: >
      sh -c "pytest"
    depends_on:
      database:
        condition: service_healthy
    volumes:
      - .env:/todolist/.env

  migrate:
    image: stashunter/todolist:${GITHUB_REF_NAME}-${GITHUB_RUN_ID}
    container_name: migrate
    command: >
      sh -c "python manage.py makemigrations && python manage.py migrate"
    depends_on:
      tests:
        condition: service_completed_successfully
    volumes:
      - .env:/todolist/.env

  api:
    image: stashunter/todolist:${GITHUB_REF_NAME}-${GITHUB_RUN_ID}
    container_name: api
    command: >
      sh -c "python manage.py collectstatic -c --no-input 
      && gunicorn diploma_project_pd12.wsgi:application -w 4 -b 0.0.0.0:8000"
    depends_on:
      migrate:
        condition: service_completed_successfully
    volumes:
      - .env:/todolist/.env
      - django_static:/todolist/static

  frontend:
    image: sermalenk/skypro-front:lesson-38
    container_name: frontend
    ports:
      - "80:80"
    depends_on:
      - api
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - django_static:/usr/share/nginx/html/static

  adminer:
    image: adminer
    container_name: adminer
    ports:
      - "8080:8080"
    depends_on:
      migrate:
        condition: service_completed_successfully

  tgbot:
    image: stashunter/todolist:${GITHUB_REF_NAME}-${GITHUB_RUN_ID}
    container_name: tgbot
    command: >
      sh -c "python manage.py runbot"
    depends_on:
      - api
    volumes:
      - .env:/todolist/.env

volumes:
  django_static: