# Generated by Django 4.2 on 2023-04-12 22:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0003_goalcomment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goal',
            name='is_deleted',
        ),
    ]
