# Generated by Django 4.2 on 2023-04-14 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0004_remove_goal_is_deleted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goalcomment',
            name='text',
            field=models.CharField(max_length=1000, verbose_name='Текст'),
        ),
    ]
