# Generated by Django 4.1.7 on 2023-04-29 15:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bot', '0002_rename_user_id_telegramuser_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='telegramuser',
            options={'verbose_name': 'Telegram аккаунт', 'verbose_name_plural': 'Telegram аккаунты'},
        ),
        migrations.RemoveField(
            model_name='telegramuser',
            name='tg_user_id',
        ),
        migrations.AddField(
            model_name='telegramuser',
            name='tg_username',
            field=models.CharField(default='default', max_length=50, verbose_name='Никнейм пользователя'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='telegramuser',
            name='tg_chat_id',
            field=models.PositiveBigIntegerField(unique=True, verbose_name='ID чата'),
        ),
        migrations.AlterField(
            model_name='telegramuser',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
